# --- !Ups

create table "questions" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "question" varchar not null,
  "opt1" varchar not null,
  "opt2" varchar not null,
  "opt3" varchar not null,
  "opt4" varchar not null,
  "answer" int not null,
  "note" varchar not null
);

insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is ?', 'this', 'that', 'there', 'here', 2, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is 1?', 'this1', 'that9', 'theref', 'here9', 3, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is -1?', 'this2', 'that5', 'therez', 'here8', 4, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is 8?', 'this3', 'that3', 'therea', 'here7', 3, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is y?', 'this5', 'that8', 'there8', 'here6', 2, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is 5?', 'this4', 'that9', 'there6', 'here5', 1, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is ,?', 'this6', 'that1', 'therex', 'here4', 2, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is v?', 'this7', 'that2', 'therev', 'here3', 3, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is t?', 'this8', 'that6', 'theren', 'here2', 4, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is 7?', 'this9', 'that4', 'there\', 'here1', 3, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is x?', 'this1-1', 'tha/t', 'there[', 'here-1', 2, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is 5?', 'this9', 'thatp', 'therep', 'here1', 1, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is ?', 'this', 'that', 'there', 'here', 2, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is 1?', 'this1', 'that9', 'theref', 'here9', 3, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is -1?', 'this2', 'that5', 'therez', 'here8', 4, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is 8?', 'this3', 'that3', 'therea', 'here7', 3, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is y?', 'this5', 'that8', 'there8', 'here6', 2, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is 5?', 'this4', 'that9', 'there6', 'here5', 1, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is ,?', 'this6', 'that1', 'therex', 'here4', 2, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is v?', 'this7', 'that2', 'therev', 'here3', 3, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is t?', 'this8', 'that6', 'theren', 'here2', 4, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is 7?', 'this9', 'that4', 'there\', 'here1', 3, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is x?', 'this1-1', 'tha/t', 'there[', 'here-1', 2, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is 5?', 'this9', 'thatp', 'therep', 'here1', 1, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is ?', 'this', 'that', 'there', 'here', 2, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is 1?', 'this1', 'that9', 'theref', 'here9', 3, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is -1?', 'this2', 'that5', 'therez', 'here8', 4, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is 8?', 'this3', 'that3', 'therea', 'here7', 3, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is y?', 'this5', 'that8', 'there8', 'here6', 2, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is 5?', 'this4', 'that9', 'there6', 'here5', 1, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is ,?', 'this6', 'that1', 'therex', 'here4', 2, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is v?', 'this7', 'that2', 'therev', 'here3', 3, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is t?', 'this8', 'that6', 'theren', 'here2', 4, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is 7?', 'this9', 'that4', 'there\', 'here1', 3, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is x?', 'this1-1', 'tha/t', 'there[', 'here-1', 2, 'houu');
insert into "questions" ("question", "opt1", "opt2", "opt3", "opt4", "answer", "note")
 values ('What is 5?', 'this9', 'thatp', 'therep', 'here1', 1, 'houu');

# --- !Downs

drop table "questions" if exists;
